name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          continue-on-error: true
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml        

    code-coverage:
        name: code-coverage
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup NodeJS Version
            uses: actions/setup-node@v3
            with:
              node-version: 18

          - name: install dependencies
            run: npm install    

          - name: Code-coverage
            continue-on-error: true
            run: npm run code-coverage
        
          - name: Archive Test Results
            uses: actions/upload-artifact@v4
            with:
              name: Code-Coverage-Result
              path: coverage
              retention-days: 5

    dev-deploy:
      name: dev-deploy
      needs: docker
      environment: 
        development
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: install kubectl
            uses: azure/setup-kubectl
            with:
              version: v1.26.0
          - name: setup k8s contetext
            uses: azure/k8s-set-context
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBECONFIG }}  
          - name: run kubectl
            run: kubectl version --short -o yaml

